# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# 语言设置为中文
lang: zh-CN

# 时区设置为上海
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 (SEO优化)
# ↓ --------------------------

title: Mebius's Tech Book # 网站大标题
tagline: 正在探索 Python 与 Spring Boot 的大四学生 # 头像下方的副标题
description: >- # 网站描述
  周泽奕的个人博客，记录计算机学习点滴、毕业设计进度以及生活琐事。

# 你的博客网址。如果你还没绑定域名，请填写：https://mebius-xy.github.io
url: "https://mebius-xy.github.io"

github:
  username: Mebius-xy # 你的 GitHub 用户名

social:
  # 你的名字，会显示在页脚版权声明处
  name: 周泽奕
  email: mebius.xy@gmail.com 
  links:
    # 第一个链接会作为版权所有者的链接
    - https://github.com/Mebius-xy 
    - https://space.bilibili.com/286718829 
     # 你可以继续添加其他链接，或者保持默认
    # 你可以继续添加其他链接，或者保持默认

# ↑ --------------------------

# 偏好配色方案
# 留空会随系统自动切换，也可以填 [light | dark] 固定一种
theme_mode: 

# 侧边栏头像设置
# 1. 确保在本地根目录下有 assets/img 文件夹
# 2. 把你的头像图片放进去（比如叫 avatar.jpg）
# 3. 然后在这里填写路径：/assets/img/avatar.jpg
avatar: /assets/img/avatar.jpg

# 文章目录（TOC）全局开关
toc: true

# 评论系统（建议先留空，等基础功能跑通后再单独配置 Giscus）
comments:
  active: giscus # 这里填 giscus，告诉主题启用它
  # 下面是 giscus 的具体配置
  giscus:
    repo: 'mebius-xy/mebius-xy.github.io' # 你的仓库名
    repo_id: 'R_kgDORuVygg'
    category: 'Announcements'
    category_id: 'DIC_kwDORuVygs4C6B4Y'
    mapping: 'pathname'
    strict: '0'
    reactions_enabled: '1'
    emit_metadata: '0'
    input_position: 'bottom'
    theme: 'preferred_color_scheme'
    lang: 'zh-CN'
    loading: 'lazy'

# 每页显示的文章数量
paginate: 10

# 基础路径（如果你是 mebius-xy.github.io，这里保持空字符串 "" 即可）
baseurl: ""

# ------------ 以下选项建议保持默认，不要轻易修改 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" 
      type: posts
    values:
      layout: post
      comments: true 
      toc: true 
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs 
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
